12

diff --git a/.github/workflows/apply.yaml b/.github/workflows/apply.yaml
--- a/.github/workflows/apply.yaml
+++ b/.github/workflows/apply.yaml
@@ -36,12 +36,14 @@ jobs:
 
       - name: Terraform Plan
         env:
-          SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}  # Pass the secret as an environment variable
+          SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}  # Pass the public key secret
+          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # Pass the private key secret
         run: |
-          terraform plan -var="ssh_public_key=${SSH_PUBLIC_KEY}" || { echo "Terraform plan failed"; exit 1; }
+          terraform plan -var="ssh_public_key=${SSH_PUBLIC_KEY}" -var="ssh_private_key=${SSH_PRIVATE_KEY}" || { echo "Terraform plan failed"; exit 1; }
 
       - name: Terraform Apply
         env:
-          SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}  # Pass the secret as an environment variable
+          SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}  # Pass the public key secret
+          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # Pass the private key secret
         run: |
-          terraform apply -auto-approve -var="ssh_public_key=${SSH_PUBLIC_KEY}" || { echo "Terraform apply failed"; exit 1; }
+          terraform apply -auto-approve -var="ssh_public_key=${SSH_PUBLIC_KEY}" -var="ssh_private_key=${SSH_PRIVATE_KEY}" || { echo "Terraform apply failed"; exit 1; }
