Update apply.yaml

diff --git a/.github/workflows/apply.yaml b/.github/workflows/apply.yaml
--- a/.github/workflows/apply.yaml
+++ b/.github/workflows/apply.yaml
@@ -23,7 +23,7 @@ jobs:
     - name: Set up Terraform
       uses: hashicorp/setup-terraform@v2
       with:
-        terraform_version: 1.5.0  # Adjust version if needed
+        terraform_version: 1.9.7  # Adjust version if needed
 
     - name: Install AWS CLI
       run: |
@@ -49,22 +49,16 @@ jobs:
     - name: Initialize Terraform
       run: terraform init
 
-    - name: Terraform Plan (Apply)
-      if: ${{ github.event.inputs.action == 'apply' }}
-      run: terraform plan 
+    - name: Terraform Plan
+      run: terraform plan
 
-    - name: Approve and Apply Plan
-      if: ${{ github.event.inputs.action == 'apply' }}
+    - name: Terraform Apply or Destroy
       run: |
-        echo "Applying Terraform plan with auto-approve... "
-        terraform apply --auto-approve -
-
-    - name: Terraform Plan (Destroy)
-      if: ${{ github.event.inputs.action == 'destroy' }}
-      run: terraform plan -destroy 
-
-    - name: Approve and Destroy
-      if: ${{ github.event.inputs.action == 'destroy' }}
-      run: |
-        echo "Destroying Terraform resources with auto-approve... "
-        terraform destroy --auto-approve tfplan
+        if [ "${{ github.event.inputs.action }}" == "apply" ]; then
+          terraform apply --auto-approve
+        elif [ "${{ github.event.inputs.action }}" == "destroy" ]; then
+          terraform destroy --auto-approve
+        else
+          echo "Invalid action. Please choose 'apply' or 'destroy'."
+          exit 1
+        fi
